const products = [
    {
        id: 0,
        title: 'Crispy',
        price: '450',
        size: 'small',
        topping: ['bacon','mushroom','pepperoni'],
        imgSrc: './Images/fav.jpg',
    },
    {
        id: 1,
        title: 'Crispy',
        price: '475',
        size: 'medium',
        topping: ['bacon','mushroom','pepperoni'],
        imgSrc: './Images/Img1.jpg',
    },
    {
        id: 2,
        title: 'Crispy',
        price: '500',
        size: 'large',
        topping: ['bacon','mushroom','pepperoni'],
        imgSrc: './Images/Img2.jpg',
    },
    {
        id: 3,
        title: 'Stuffed',
        price: '480',
        size: 'small',
        topping: ['bacon','mushroom','pepperoni'],
        imgSrc: './Images/Img3.jpg',
    },
    {
        id: 4,
        title: 'Stuffed',
        price: '500',
        size: 'medium',
        topping: ['bacon','mushroom','pepperoni'],
        imgSrc: './Images/Img4.jpg',
    },
    {
        id: 5,
        title: 'Stuffed',
        price: '530',
        size: 'large',
        topping: ['bacon','mushroom','pepperoni'],
        imgSrc: './Images/Img2.jpg',
    },
    {
        id: 6,
        title: 'Gluten free',
        price: '380',
        size: 'small',
        topping: ['bacon','mushroom','pepperoni'],
        imgSrc: './Images/Img1.jpg',
    },
    {
        id: 7,
        title: 'Gluten free',
        price: '420',
        size: 'medium',
        topping: ['bacon','mushroom','pepperoni'],
        imgSrc: './Images/Img3.jpg',
    },
    {
        id: 8,
        title: 'Gluten free',
        price: '490',
        size: 'large',
        topping: ['bacon','mushroom','pepperoni'],
        imgSrc: './Images/Img4.jpg',
    },
   
]